

-- CREATE - cRIAR OBJETOS DE BANCO (DATABASE, SCHEMA, TABLEAS, VIEW,...)
-- CREATE SCHEMA TEST
-- DROP - aPAGA OBJETOS DO BANCO (OS MESMOS) 

-- ALTER (OBJETO ) NOME_OBJETO (aCÃO - ADD, DROP) (oBJETO A MANIPULA ) 
-- ALTER TABLE USUARIO ADD COLUMN SOBRENOME VARCHAR(50)
-- ALTER TAVLE USUARIO DROP COLUMN SOBRENME           


CREATE TABLE CLIENTE(
  ID SERIAL PRIMARY KEY, 
  NOME VARCHAR(200),
  SENHA VARCHAR (50),
  EMAIL VARCHAR (150), 
  CPF VARCHAR(11) UNIQUE
)


CREATE TABLE TELEFONE(
  ID SERIAL PRIMARY KEY, 
  TELEFONE VARCHAR(11), 
  CLIENTE_ID INT REFERENCES CLIENTE(ID)
)

INSERT INTO CLIENTE (NOME, EMAIL, SENHA, CPF)
VALUES ('VITOR', 'VITOR@LASSEN', '123', '1234567')

INSERT INTO CLIENTE (NOME, EMAIL, CPF)
VALUES ('VITOR', 'VITOR@LASSEN', '12345678')
INSERT INTO CLIENTE 
VALUES (3, 'MIKA', 'MIKA@TIO', '123', '8765421')

SELECT * FROM CLIENTE


INSERT INTO TELEFONE (TELEFONE, CLIENTE_ID)
VALUES ('123',1), ('456',1)

INSERT INTO TELEFONE (TELEFONE, CLIENTE_ID)
VALUES ('456',3)

SELECT * FROM TELEFONE

INSERT INTO TELEFONE (TELEFONE, CLIENTE_ID)
VALUES ('456',1)

DELETE FROM TELEFONE
WHERE ID = 4

ALTER TABLE TELEFONE DROP COLUMN ID

ALTER TABLE TELEFONE ADD CONSTRAINT PK_TELEFONE_CLIENTEID PRIMARY KEY (TELEFONE, CLIENTE_ID)